using System.Collections.ObjectModel;
using UBViews.Models;

namespace UBViews.State;
public partial class TitlesFilter
{
    public ObservableCollection<PaperDto> PaperDtos { get; set; }

    // CStor
    public TitlesFilter() { }

    public async Task Create()
    {
        await Task.Run(() =>
        {
            PaperDtos = new ObservableCollection<PaperDto>()
            {
                new PaperDto { Id = 0, Title = "Foreword", Author = "Divine Counselor", PartId = 0, PartTitle = "Foreword Material", TimeSpan = "0:0:0.0_1:6:39.0"},
                new PaperDto { Id = 1, Title = "The Universal Father", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:45:5.0"},
                new PaperDto { Id = 2, Title = "The Nature of God", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:45:3.0"},
                new PaperDto { Id = 3, Title = "The Attributes of God", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:38:33.0"},
                new PaperDto { Id = 4, Title = "God’s Relation to the Universe", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:29:3.0"},
                new PaperDto { Id = 5, Title = "God’s Relation to the Individual", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:40:44.0"},
                new PaperDto { Id = 6, Title = "The Eternal Son", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:30:33.0"},
                new PaperDto { Id = 7, Title = "Relation of the Eternal Son to the Universe", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:32:41.0"},
                new PaperDto { Id = 8, Title = "The Infinite Spirit", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:30:49.0"},
                new PaperDto { Id = 9, Title = "Relation of the Infinite Spirit  to the Universe", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:36:48.0"},
                new PaperDto { Id = 10, Title = "The Paradise Trinity", Author = "Universal Censor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:35:16.0"},
                new PaperDto { Id = 11, Title = "The Eternal Isle of Paradise", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:38:4.0"},
                new PaperDto { Id = 12, Title = "The Universe of Universes", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:55:22.0"},
                new PaperDto { Id = 13, Title = "The Sacred Spheres of Paradise", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:32:14.0"},
                new PaperDto { Id = 14, Title = "The Central and Divine Universe", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:41:9.0"},
                new PaperDto { Id = 15, Title = "The Seven Superuniverses", Author = "Universal Censor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_1:8:13.0"},
                new PaperDto { Id = 16, Title = "The Seven Master Spirits", Author = "Universal Censor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:47:8.0"},
                new PaperDto { Id = 17, Title = "The Seven Supreme Spirit Groups", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:33:42.0"},
                new PaperDto { Id = 18, Title = "The Supreme Trinity Personalities", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:24:4.0"},
                new PaperDto { Id = 19, Title = "The Co-ordinate Trinity-Origin Beings", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:32:25.0"},
                new PaperDto { Id = 20, Title = "The Paradise Sons Of God", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:39:9.0"},
                new PaperDto { Id = 21, Title = "The Paradise Creator Sons", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:31:15.0"},
                new PaperDto { Id = 22, Title = "The Trinitized Sons of God", Author = "Mighty Messenger", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:44:17.0"},
                new PaperDto { Id = 23, Title = "The Solitary Messengers", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:25:51.0"},
                new PaperDto { Id = 24, Title = "Higher Personalities of the Infinite Spirit", Author = "Divine Counselor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:28:46.0"},
                new PaperDto { Id = 25, Title = "The Messenger Hosts of Space", Author = "One High in Authority", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:42:29.0"},
                new PaperDto { Id = 26, Title = "Ministering Spirits of the Central Universe", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:45:43.0"},
                new PaperDto { Id = 27, Title = "Ministry of the Primary Supernaphim", Author = "Perfector of Wisdom", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:27:47.0"},
                new PaperDto { Id = 28, Title = "Ministering Spirits of the Superuniverses", Author = "Mighty Messenger", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:46:31.0"},
                new PaperDto { Id = 29, Title = "The Universe Power Directors", Author = "Universal Censor", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:40:26.0"},
                new PaperDto { Id = 30, Title = "Personalities of the Grand Universe", Author = "Mighty Messenger", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:49:40.0"},
                new PaperDto { Id = 31, Title = "The Corps of the Finality", Author = "Divine Counselor and One Without Name and Number", PartId = 1, PartTitle = "The Central and Superuniverses", TimeSpan = "0:0:0.0_0:35:53.0"},
                new PaperDto { Id = 32, Title = "The Evolution of Local Universes", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:31:59.0"},
                new PaperDto { Id = 33, Title = "Administration of the Local Universe", Author = "Chief of Archangels", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:27:59.0"},
                new PaperDto { Id = 34, Title = "The Local Universe Mother Spirit", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:37:8.0"},
                new PaperDto { Id = 35, Title = "The Local Universe Sons of God", Author = "Chief of Archangels", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:36:52.0"},
                new PaperDto { Id = 36, Title = "The Life Carriers", Author = "Vorondadek Son", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:33:37.0"},
                new PaperDto { Id = 37, Title = "Personalities of the Local Universe", Author = "Brilliant Evening Star", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:38:49.0"},
                new PaperDto { Id = 38, Title = "Ministering Spirits of the Local Universe", Author = "Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:28:39.0"},
                new PaperDto { Id = 39, Title = "The Seraphic Hosts", Author = "Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:56:50.0"},
                new PaperDto { Id = 40, Title = "The Ascending Sons of God", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:42:2.0"},
                new PaperDto { Id = 41, Title = "Physical Aspects of the Local Universe", Author = "Archangel", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:44:37.0"},
                new PaperDto { Id = 42, Title = "Energy—Mind and Matter", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_1:6:53.0"},
                new PaperDto { Id = 43, Title = "The Constellations", Author = "Malavatia Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:41:10.0"},
                new PaperDto { Id = 44, Title = "The Celestial Artisans", Author = "Archangel", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:44:8.996"},
                new PaperDto { Id = 45, Title = "The Local System Administration", Author = "Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "00:00:00.00_00:00:00.00"},
                new PaperDto { Id = 46, Title = "The Local System Headquarters", Author = "Archangel", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:37:18.386"},
                new PaperDto { Id = 47, Title = "The Seven Mansion Worlds", Author = "Brilliant Evening Star", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:38:51.757"},
                new PaperDto { Id = 48, Title = "The Morontia Life", Author = "Archangel", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_1:2:25.372"},
                new PaperDto { Id = 49, Title = "The Inhabited Worlds", Author = "Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:45:10.143"},
                new PaperDto { Id = 50, Title = "The Planetary Princes", Author = "Secondary Lanonandek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:25:22.391"},
                new PaperDto { Id = 51, Title = "The Planetary Adams", Author = "Secondary Lanonandek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:30:54.589"},
                new PaperDto { Id = 52, Title = "Planetary Mortal Epochs", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:43:58.620"},
                new PaperDto { Id = 53, Title = "The Lucifer Rebellion", Author = "Manovandet Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:41:10.23"},
                new PaperDto { Id = 54, Title = "Problems of the Lucifer Rebellion", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:26:56.325"},
                new PaperDto { Id = 55, Title = "The Spheres of Light and Life", Author = "Mighty Messenger", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:57:35.62"},
                new PaperDto { Id = 56, Title = "Universal Unity", Author = "Mighty Messenger and Machiventa Melchizedek", PartId = 2, PartTitle = "The Local Universe", TimeSpan = "0:0:0.0_0:44:37.918"},
                new PaperDto { Id = 57, Title = "The Origin of Urantia", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:44:43.849"},
                new PaperDto { Id = 58, Title = "Life Establishment on Urantia", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:28:22.609"},
                new PaperDto { Id = 59, Title = "The Marine-Life Era on Urantia", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:43:8.787"},
                new PaperDto { Id = 60, Title = "Urantia During the Early Land-Life Era", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:27:42.63"},
                new PaperDto { Id = 61, Title = "The Mammalian Era on Urantia", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:35:18.66"},
                new PaperDto { Id = 62, Title = "The Dawn Races of Early Man", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:29:57.793"},
                new PaperDto { Id = 63, Title = "The First Human Family", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:24:24.353"},
                new PaperDto { Id = 64, Title = "The Evolutionary Races of Color", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:41:0.982"},
                new PaperDto { Id = 65, Title = "The Overcontrol of Evolution", Author = "Life Carrier", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:37:37.454"},
                new PaperDto { Id = 66, Title = "The Planetary Prince of Urantia", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:47:37.884"},
                new PaperDto { Id = 67, Title = "The Planetary Rebellion", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:33:17.645"},
                new PaperDto { Id = 68, Title = "The Dawn of Civilization", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:32:3.5"},
                new PaperDto { Id = 69, Title = "Primitive Human Institutions", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:39:9.209"},
                new PaperDto { Id = 70, Title = "The Evolution of Human Government", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:55:32.896"},
                new PaperDto { Id = 71, Title = "Development of the State", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:23:46.504"},
                new PaperDto { Id = 72, Title = "Government on a Neighboring Planet", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:43:1.860"},
                new PaperDto { Id = 73, Title = "The Garden of Eden", Author = "Solonia", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:21:37.364"},
                new PaperDto { Id = 74, Title = "Adam and Eve", Author = "Solonia", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:37:19.767"},
                new PaperDto { Id = 75, Title = "The Default of Adam and Eve", Author = "Solonia", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:28:16.719"},
                new PaperDto { Id = 76, Title = "The Second Garden", Author = "Solonia", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:25:56.217"},
                new PaperDto { Id = 77, Title = "The Midway Creatures", Author = "Archangel", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:45:37.916"},
                new PaperDto { Id = 78, Title = "The Violet Race after the Days of Adam", Author = "Archangel", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:33:31.736"},
                new PaperDto { Id = 79, Title = "Andite Expansion in the Orient", Author = "Archangel", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:40:42.888"},
                new PaperDto { Id = 80, Title = "Andite Expansion in the Occident", Author = "Archangel", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:38:8.356"},
                new PaperDto { Id = 81, Title = "Development of Modern Civilization", Author = "Archangel", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:44:30.877"},
                new PaperDto { Id = 82, Title = "The Evolution of Marriage", Author = "Chief of Seraphim", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:29:21.845"},
                new PaperDto { Id = 83, Title = "The Marriage Institution", Author = "Chief of Seraphim", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:31:38.446"},
                new PaperDto { Id = 84, Title = "Marriage and Family Life", Author = "Chief of Seraphim", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:44:52.12"},
                new PaperDto { Id = 85, Title = "The Origins of Worship", Author = "Brilliant Evening Star", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:18:55.138"},
                new PaperDto { Id = 86, Title = "Early Evolution of Religion", Author = "Brilliant Evening Star", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:27:11.574"},
                new PaperDto { Id = 87, Title = "The Ghost Cults", Author = "Brilliant Evening Star", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:32:4.211"},
                new PaperDto { Id = 88, Title = "Fetishes, Charms, and Magic", Author = "Brilliant Evening Star", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:23:24.518"},
                new PaperDto { Id = 89, Title = "Sin, Sacrifice, and Atonement", Author = "Brilliant Evening Star", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:41:42.867"},
                new PaperDto { Id = 90, Title = "Shamanism—Medicine Men and Priests", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:26:17.625"},
                new PaperDto { Id = 91, Title = "The Evolution of Prayer", Author = "Chief of Midwayers", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:33:32.7"},
                new PaperDto { Id = 92, Title = "The Later Evolution of Religion", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:42:0.453"},
                new PaperDto { Id = 93, Title = "Machiventa Melchizedek", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:45:57.521"},
                new PaperDto { Id = 94, Title = "The Melchizedek Teachings in the Orient", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:56:44.833"},
                new PaperDto { Id = 95, Title = "The Melchizedek Teachings in the Levant", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:35:58.996"},
                new PaperDto { Id = 96, Title = "Yahweh—God of the Hebrews", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:32:43.344"},
                new PaperDto { Id = 97, Title = "Evolution of the God Concept among the Hebrews", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:53:38.307"},
                new PaperDto { Id = 98, Title = "The Melchizedek Teachings in the Occident", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:29:44.579"},
                new PaperDto { Id = 99, Title = "The Social Problems of Religion", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:26:27.118"},
                new PaperDto { Id = 100, Title = "Religion in Human Experience", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:39:33.535"},
                new PaperDto { Id = 101, Title = "The Real Nature of Religion", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:52:14.622"},
                new PaperDto { Id = 102, Title = "The Foundations of Religious Faith", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:42:19.173"},
                new PaperDto { Id = 103, Title = "The Reality of Religious Experience", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:52:32.807"},
                new PaperDto { Id = 104, Title = "Growth of the Trinity Concept", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:31:37.914"},
                new PaperDto { Id = 105, Title = "Deity and Reality", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:35:39.551"},
                new PaperDto { Id = 106, Title = "Universe Levels of Reality", Author = "Melchizedek", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:52:39.511"},
                new PaperDto { Id = 107, Title = "Origin and Nature of Thought Adjusters", Author = "Solitary Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:31:33.589"},
                new PaperDto { Id = 108, Title = "Mission and Ministry of Thought Adjusters", Author = "Solitary Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:34:5.601"},
                new PaperDto { Id = 109, Title = "Relation of Adjusters to Universe Creatures", Author = "Solitary Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:27:33.630"},
                new PaperDto { Id = 110, Title = "Relation of Adjusters to Individual Mortals", Author = "Solitary Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:45:23.38"},
                new PaperDto { Id = 111, Title = "The Adjuster and the Soul", Author = "Solitary Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:37:42.814"},
                new PaperDto { Id = 112, Title = "Personality Survival", Author = "Solitary Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:59:13.456"},
                new PaperDto { Id = 113, Title = "Seraphic Guardians of Destiny", Author = "Chief of Seraphim", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:31:21.230"},
                new PaperDto { Id = 114, Title = "Seraphic Planetary Government", Author = "Chief of Seraphim", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:34:38.35"},
                new PaperDto { Id = 115, Title = "The Supreme Being", Author = "Mighty Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:28:30.960"},
                new PaperDto { Id = 116, Title = "The Almighty Supreme", Author = "Mighty Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:32:56.607"},
                new PaperDto { Id = 117, Title = "God the Supreme", Author = "Mighty Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_1:0:9.458"},
                new PaperDto { Id = 118, Title = "Supreme and Ultimate—Time and Space", Author = "Mighty Messenger", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:51:42.766"},
                new PaperDto { Id = 119, Title = "The Bestowals of Christ Michael", Author = "Chief of Evening Stars", PartId = 3, PartTitle = "The History of Urantia", TimeSpan = "0:0:0.0_0:40:27.90"},
                new PaperDto { Id = 120, Title = "The Bestowal of Michael on Urantia", Author = "Mantutia Melchizedek", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:32:40.481"},
                new PaperDto { Id = 121, Title = "The Times of Michael’s Bestowal", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:40:46.521"},
                new PaperDto { Id = 122, Title = "Birth and Infancy of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:36:37.574"},
                new PaperDto { Id = 123, Title = "The Early Childhood of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:38:52.198"},
                new PaperDto { Id = 124, Title = "The Later Childhood of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:37:15.597"},
                new PaperDto { Id = 125, Title = "Jesus at Jerusalem", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:28:59.139"},
                new PaperDto { Id = 126, Title = "The Two Crucial Years", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:32:36.505"},
                new PaperDto { Id = 127, Title = "The Adolescent Years", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:43:15.224"},
                new PaperDto { Id = 128, Title = "Jesus’ Early Manhood", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:44:58.619"},
                new PaperDto { Id = 129, Title = "The Later Adult Life of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:27:1.978"},
                new PaperDto { Id = 130, Title = "On the Way to Rome", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:50:55.163"},
                new PaperDto { Id = 131, Title = "The World’s Religions", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:52:44.910"},
                new PaperDto { Id = 132, Title = "The Sojourn at Rome", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:49:3.607"},
                new PaperDto { Id = 133, Title = "The Return from Rome", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:56:27.65"},
                new PaperDto { Id = 134, Title = "The Transition Years", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:44:34.440"},
                new PaperDto { Id = 135, Title = "John the Baptist", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:46:35.994"},
                new PaperDto { Id = 136, Title = "Baptism and the Forty Days", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:56:50.683"},
                new PaperDto { Id = 137, Title = "Tarrying Time in Galilee", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:46:40.275"},
                new PaperDto { Id = 138, Title = "Training the Kingdom’s Messengers", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:35:46.601"},
                new PaperDto { Id = 139, Title = "The Twelve Apostles", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_1:15:12.229"},
                new PaperDto { Id = 140, Title = "The Ordination of the Twelve", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_1:13:31.339"},
                new PaperDto { Id = 141, Title = "Beginning the Public Work", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:32:49.396"},
                new PaperDto { Id = 142, Title = "The Passover at Jerusalem", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:36:54.854"},
                new PaperDto { Id = 143, Title = "Going Through Samaria", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:38:20.920"},
                new PaperDto { Id = 144, Title = "At Gilboa and in the Decapolis", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:35:29.545"},
                new PaperDto { Id = 145, Title = "Four Eventful Days at Capernaum", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:31:32.769"},
                new PaperDto { Id = 146, Title = "First Preaching Tour of Galilee", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:38:17.408"},
                new PaperDto { Id = 147, Title = "The Interlude Visit to Jerusalem", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:34:17.200"},
                new PaperDto { Id = 148, Title = "Training Evangelists at Bethsaida", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:39:25.459"},
                new PaperDto { Id = 149, Title = "The Second Preaching Tour", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:35:50.765"},
                new PaperDto { Id = 150, Title = "The Third Preaching Tour", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:33:3.610"},
                new PaperDto { Id = 151, Title = "Tarrying and Teaching by the Seaside", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:32:5.386"},
                new PaperDto { Id = 152, Title = "Events Leading up to the Capernaum Crisis", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:29:39.779"},
                new PaperDto { Id = 153, Title = "The Crisis at Capernaum", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:36:3.97"},
                new PaperDto { Id = 154, Title = "Last Days at Capernaum", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:25:7.431"},
                new PaperDto { Id = 155, Title = "Fleeing Through Northern Galilee", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:35:55.916"},
                new PaperDto { Id = 156, Title = "The Sojourn at Tyre and Sidon", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:29:11.428"},
                new PaperDto { Id = 157, Title = "At Caesarea-Philippi", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:29:36.842"},
                new PaperDto { Id = 158, Title = "The Mount of Transfiguration", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:35:19.920"},
                new PaperDto { Id = 159, Title = "The Decapolis Tour", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:36:57.875"},
                new PaperDto { Id = 160, Title = "Rodan of Alexandria", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:43:50.308"},
                new PaperDto { Id = 161, Title = "Further Discussions with Rodan", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:18:19.154"},
                new PaperDto { Id = 162, Title = "At the Feast of Tabernacles", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:40:14.311"},
                new PaperDto { Id = 163, Title = "Ordination of the Seventy at Magadan", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:34:2.186"},
                new PaperDto { Id = 164, Title = "At the Feast of Dedication", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:27:35.130"},
                new PaperDto { Id = 165, Title = "The Perean Mission Begins", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:28:40.412"},
                new PaperDto { Id = 166, Title = "Last Visit to Northern Perea", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:25:56.250"},
                new PaperDto { Id = 167, Title = "The Visit to Philadelphia", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:32:1.169"},
                new PaperDto { Id = 168, Title = "The Resurrection of Lazarus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:28:12.893"},
                new PaperDto { Id = 169, Title = "Last Teaching at Pella", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:28:12.135"},
                new PaperDto { Id = 170, Title = "The Kingdom of Heaven", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:31:48.332"},
                new PaperDto { Id = 171, Title = "On the Way to Jerusalem", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:38:50.256"},
                new PaperDto { Id = 172, Title = "Going into Jerusalem", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:32:26.97"},
                new PaperDto { Id = 173, Title = "Monday in Jerusalem", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:29:20.129"},
                new PaperDto { Id = 174, Title = "Tuesday Morning in the Temple", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:30:19.148"},
                new PaperDto { Id = 175, Title = "The Last Temple Discourse", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:26:21.310"},
                new PaperDto { Id = 176, Title = "Tuesday Evening on Mount Olivet", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:29:9.587"},
                new PaperDto { Id = 177, Title = "Wednesday, the Rest Day", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:30:46.561"},
                new PaperDto { Id = 178, Title = "Last Day at the Camp", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:22:57.753"},
                new PaperDto { Id = 179, Title = "The Last Supper", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:25:11.569"},
                new PaperDto { Id = 180, Title = "The Farewell Discourse", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:35:59.215"},
                new PaperDto { Id = 181, Title = "Final Admonitions and Warnings", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:36:59.750"},
                new PaperDto { Id = 182, Title = "In Gethsemane", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:27:21.798"},
                new PaperDto { Id = 183, Title = "The Betrayal and Arrest of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:24:26.973"},
                new PaperDto { Id = 184, Title = "Before the Sanhedrin Court", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:27:56.667"},
                new PaperDto { Id = 185, Title = "The Trial Before Pilate", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:37:56.943"},
                new PaperDto { Id = 186, Title = "Just Before the Crucifixion", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:23:52.248"},
                new PaperDto { Id = 187, Title = "The Crucifixion", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:27:21.774"},
                new PaperDto { Id = 188, Title = "The Time of the Tomb", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:26:40.94"},
                new PaperDto { Id = 189, Title = "The Resurrection", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:28:53.558"},
                new PaperDto { Id = 190, Title = "Morontia Appearances of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:24:31.792"},
                new PaperDto { Id = 191, Title = "Appearances to the Apostles and Other Leaders", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:28:8.646"},
                new PaperDto { Id = 192, Title = "Appearances in Galilee", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:22:57.588"},
                new PaperDto { Id = 193, Title = "Final Appearances and Ascension", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:24:30.708"},
                new PaperDto { Id = 194, Title = "Bestowal of the Spirit of Truth", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:37:17.580"},
                new PaperDto { Id = 195, Title = "After Pentecost", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_1:4:38.681"},
                new PaperDto { Id = 196, Title = "The Faith of Jesus", Author = "Midwayer Commission", PartId = 4, PartTitle = "The Life and Teachings of Jesus", TimeSpan = "0:0:0.0_0:38:53.736"},
            };
        });
    }
}

